be15-4th-project/be15-4th-DAO-NBTI-backend

- NBTI/src/main/java/com/dao/nbti/problem/domain/aggregate/AnswerType.java
- NBTI/src/main/java/com/dao/nbti/problem/domain/aggregate/Category.java
- NBTI/src/main/java/com/dao/nbti/problem/domain/aggregate/IsDeleted.java
- NBTI/src/main/java/com/dao/nbti/problem/domain/aggregate/Problem.java
- NBTI/src/main/java/com/dao/nbti/problem/domain/repository/AnswerTypeRepository.java
- NBTI/src/main/java/com/dao/nbti/problem/domain/repository/CategoryRepository.java
- NBTI/src/main/java/com/dao/nbti/problem/domain/repository/ProblemRepository.java
- NBTI/src/main/java/com/dao/nbti/problem/domain/repository/repo.java
📌 개요
문제 관련 entity, repository 생성
🔨 주요 변경 사항
- 문제, 분야, 답안 유형 entity 생성
- 문제, 분야, 답안 유형 repository 생성
✅ 리뷰 요청 사항
- entity, repository 구성 올바른지
⭐ 관련 이슈
null
> Feature/admin 문제 Entity 생성 

- NBTI/src/main/java/com/dao/nbti/common/config/SecurityConfig.java
- NBTI/src/main/java/com/dao/nbti/common/exception/ErrorCode.java
- NBTI/src/main/java/com/dao/nbti/user/application/controller/UserController.java
- NBTI/src/main/java/com/dao/nbti/user/application/dto/UserCreateRequest.java
- NBTI/src/main/java/com/dao/nbti/user/application/service/UserService.java
- NBTI/src/main/java/com/dao/nbti/user/domain/aggregate/IsDeleted.java
- NBTI/src/main/java/com/dao/nbti/user/domain/aggregate/User.java
- NBTI/src/main/java/com/dao/nbti/user/domain/repository/UserRepository.java
- NBTI/src/main/java/com/dao/nbti/user/exception/UserException.java
closes #1 
📌 개요
회원 가입 기능을 위한 기능 구현
🔨 주요 변경 사항
UserController.signup 구현
UserService.createUser 구현
SecurityConfig에서 authenticated를 permitAll로 변경
User Context Entity 수정
✅ 리뷰 요청 사항
예외처리 확인 및 정상 회원가입 여부
⭐ 관련 이슈
#1
> feat: 회원가입 기능 구현

- NBTI/src/main/java/com/dao/nbti/objection/domain/aggregate/Objection.java
- NBTI/src/main/java/com/dao/nbti/objection/domain/aggregate/Status.java
- NBTI/src/main/java/com/dao/nbti/objection/domain/aggregate/myentity.java
- NBTI/src/main/java/com/dao/nbti/objection/domain/repository/ObjectionRepository.java
- NBTI/src/main/java/com/dao/nbti/objection/domain/repository/repo.java
closes 
---
📌 개요
🔨 주요 변경 사항
Objection.java 구현
Status.java 구현
ObjectionRepository.java 구현
✅ 리뷰 요청 사항
엔티티 어노테이션 및 데이터 타입 확인
⭐ 관련 이슈
#
> init :  이의 제기 엔티티 및 레포지토리 생성

- NBTI/src/main/java/com/dao/nbti/test/domain/aggregate/IsCorrect.java
- NBTI/src/main/java/com/dao/nbti/test/domain/aggregate/TestProblem.java
- NBTI/src/main/java/com/dao/nbti/test/domain/aggregate/TestResult.java
- NBTI/src/main/java/com/dao/nbti/test/domain/repository/TestProblemRepository.java
- NBTI/src/main/java/com/dao/nbti/test/domain/repository/TestResultRepository.java
- NBTI/src/main/java/com/dao/nbti/test/domain/repository/repo.java
closes 
---
📌 개요
검사 관련 엔티티 및 레포지토리 생성
🔨 주요 변경 사항
- TestProblem 엔티티 생성
- TestResult 엔티티 생성
- TestProblemRepository 생성
- TestResultRepository 생성
- 패키지 공유를 위한 repo 삭제
- isCorrect의 enum 추가 (TestProblem 엔티티에서 사용)
✅ 리뷰 요청 사항
엔티티 검수
⭐ 관련 이슈
#
> init : 검사 엔티티 및 레포지토리 생성

- NBTI/build.gradle
- NBTI/src/main/java/com/dao/nbti/common/config/SwaggerConfig.java
- NBTI/src/main/resources/application.yml
closes 
---
📌 개요
swagger API 의존성 및 설정 추가
🔨 주요 변경 사항
- build.gradle에 springdoc 의존성 추가
- application.yml에 swagger 관련 설정 추가
- SwaggerConfig 파일 추가
✅ 리뷰 요청 사항
누락된 swagger 설정 확인
⭐ 관련 이슈
> init : swagger API 의존성 및 설정 추가

- NBTI/src/main/java/com/dao/nbti/study/application/controller/StudyController.java
- NBTI/src/main/java/com/dao/nbti/study/application/controller/controller.java
- NBTI/src/main/java/com/dao/nbti/study/application/dto/dto.java
- NBTI/src/main/java/com/dao/nbti/study/application/service/StudyService.java
- NBTI/src/main/java/com/dao/nbti/study/application/service/service.java
- NBTI/src/main/java/com/dao/nbti/study/domain/aggregate/IsCorrect.java
- NBTI/src/main/java/com/dao/nbti/study/domain/aggregate/Study.java
- NBTI/src/main/java/com/dao/nbti/study/domain/aggregate/StudyResult.java
- NBTI/src/main/java/com/dao/nbti/study/domain/repository/StudyRepository.java
- NBTI/src/main/java/com/dao/nbti/study/domain/repository/StudyResultRepository.java
- NBTI/src/main/java/com/dao/nbti/study/domain/repository/repo.java
---
📌 개요
학습 기능 초기 구현
🔨 주요 변경 사항
- Study, StudyResult Entity 생성(Builder 애노테이션 미리 적용)
- StudyController
- StudyService
- StudyRepository, StudyResultRepository 생성
✅ 리뷰 요청 사항
> feat: 학습 기능 초기 구현 - Entity, Controller, Service, Repository 생성

- NBTI/src/main/java/com/dao/nbti/user/domain/aggregate/PointHistory.java
- NBTI/src/main/java/com/dao/nbti/user/domain/aggregate/PointType.java
---
📌 개요
🔨 주요 변경 사항
PointHistory.java
PointType.java
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
> init: point 엔티티 업로드

- NBTI/src/main/java/com/dao/nbti/problem/domain/aggregate/Category.java
- NBTI/src/main/java/com/dao/nbti/study/domain/aggregate/Study.java
---
📌 개요
- 카테고리 엔티티에 분야 설명 컬럼 추가
🔨 주요 변경 사항
- 카테고리 엔티티에 분야 설명 컬럼 추가
> feat: 카테고리 엔티티에 분야 설명 컬럼 추가

- NBTI/build.gradle
- NBTI/src/main/java/com/dao/nbti/test/application/controller/TestController.java
- NBTI/src/main/java/com/dao/nbti/test/application/controller/controller.java
- NBTI/src/main/java/com/dao/nbti/test/application/dto/dto.java
- NBTI/src/main/java/com/dao/nbti/test/application/dto/request/AiAnswerCreateRequest.java
- NBTI/src/main/java/com/dao/nbti/test/application/dto/response/AiAnswerResponse.java
- NBTI/src/main/java/com/dao/nbti/test/application/service/TestAiAnswerService.java
- NBTI/src/main/java/com/dao/nbti/test/application/service/TestAiAnswerServiceImpl.java
- NBTI/src/main/java/com/dao/nbti/test/application/service/service.java
- NBTI/src/main/resources/application.yml
closes #39 
---
📌 개요
ai로 지능 검사 요청 
🔨 주요 변경 사항
- `build.gradle`에 ai 의존성 추가
- `application.yml`에 api_key 추가하기
- `TestController`에 ai 검사 요청
- `TestAiAnswerService`와 `TestAiAnswerServiceImpl` 생성  : ai를 실제로 불러와서 로직 처리를 하는 부분 
- AI 응답 관련 요청 생성(AiAnswerCreateRequest), 응답(AiAnswerResponse ) 객체 생성
- 필요 없는 초기 파일들 삭제 
✅ 리뷰 요청 사항
로직 구현이 이상 없는지 확인 
⭐ 관련 이슈
#39
> feat : ai로 지능 검사 요청

- NBTI/src/main/java/com/dao/nbti/problem/application/controller/AdminProblemController.java
- NBTI/src/main/java/com/dao/nbti/problem/application/controller/controller.java
- NBTI/src/main/java/com/dao/nbti/problem/application/dto/dto.java
- NBTI/src/main/java/com/dao/nbti/problem/application/dto/request/ProblemSearchRequest.java
- NBTI/src/main/java/com/dao/nbti/problem/application/dto/response/ProblemDTO.java
- NBTI/src/main/java/com/dao/nbti/problem/application/dto/response/ProblemListResponse.java
- NBTI/src/main/java/com/dao/nbti/problem/application/dto/response/ProblemSummaryDTO.java
- NBTI/src/main/java/com/dao/nbti/problem/application/service/AdminProblemService.java
- NBTI/src/main/java/com/dao/nbti/problem/application/service/service.java
- NBTI/src/main/java/com/dao/nbti/problem/domain/repository/ProblemRepositoryCustom.java
- NBTI/src/main/java/com/dao/nbti/problem/domain/repository/ProblemRepositoryImpl.java
- NBTI/src/main/java/com/dao/nbti/user/domain/aggregate/Gender.java
closes #027
---
📌 개요
- 문제 목록 조회 기능 구현
🔨 주요 변경 사항
- api, 컨트롤러, 서비스, repository 등 작성 완료
- postman 및 DB에 insert한 dummy data로 기능 테스트 완료
✅ 리뷰 요청 사항
⭐ 관련 이슈
#027
> Feature/admin 문제 목록 조회 기능 구현

- NBTI/src/main/java/com/dao/nbti/common/jwt/JwtTokenProvider.java
closes #56
---
📌 개요
JwtTokenProvider 의 LoginId 필드명을 수정
🔨 주요 변경 사항
LoginId 필드명을 UserId로 수정
✅ 리뷰 요청 사항
필드명 수정 여부
⭐ 관련 이슈
#56
> fix: JwtTokenProvider 변수명 수정

- NBTI/src/main/java/com/dao/nbti/common/exception/ErrorCode.java
- NBTI/src/main/java/com/dao/nbti/study/application/controller/StudyResultController.java
- NBTI/src/main/java/com/dao/nbti/study/application/dto/request/StudySearchCondition.java
- NBTI/src/main/java/com/dao/nbti/study/application/dto/response/StudyDetailResponse.java
- NBTI/src/main/java/com/dao/nbti/study/application/dto/response/StudyProblemDetail.java
- NBTI/src/main/java/com/dao/nbti/study/application/dto/response/StudySummaryResponse.java
- NBTI/src/main/java/com/dao/nbti/study/application/service/StudyResultService.java
- NBTI/src/main/java/com/dao/nbti/study/application/service/StudyResultServiceImpl.java
- NBTI/src/main/java/com/dao/nbti/study/domain/aggregate/Study.java
- NBTI/src/main/java/com/dao/nbti/study/domain/repository/StudyRepository.java
- NBTI/src/main/java/com/dao/nbti/study/domain/repository/StudyResultRepository.java
- NBTI/src/main/java/com/dao/nbti/test/application/dto/response/TestResultDetailResponse.java
closes #15
---
📌 개요
🔨 주요 변경 사항
- StudyResultController.java
- StudySearchCondition.java
- StudySummaryResponse.java
- StudyResultService.java
- StudyResultServiceImpl.java
- StudyRepository.java
- StudyResultRepository.java
- StudyException,java
- ErrorCode.java
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
> feat: 학습 결과 목록 조회 기능 구현

- NBTI/src/main/java/com/dao/nbti/common/exception/ErrorCode.java
- NBTI/src/main/java/com/dao/nbti/objection/application/controller/ObjectionController.java
- NBTI/src/main/java/com/dao/nbti/objection/application/controller/controller.java
- NBTI/src/main/java/com/dao/nbti/objection/application/dto/dto.java
- NBTI/src/main/java/com/dao/nbti/objection/application/dto/request/ObjectionCreateRequest.java
- NBTI/src/main/java/com/dao/nbti/objection/application/dto/response/ObjectionCreateResponse.java
- NBTI/src/main/java/com/dao/nbti/objection/application/dto/response/ObjectionDetailResponse.java
- NBTI/src/main/java/com/dao/nbti/objection/application/dto/response/ObjectionSummaryResponse.java
- NBTI/src/main/java/com/dao/nbti/objection/application/service/ObjectionService.java
- NBTI/src/main/java/com/dao/nbti/objection/application/service/ObjectionServiceImpl.java
- NBTI/src/main/java/com/dao/nbti/objection/application/service/service.java
- NBTI/src/main/java/com/dao/nbti/objection/domain/aggregate/Objection.java
- NBTI/src/main/java/com/dao/nbti/objection/domain/repository/ObjectionRepository.java
- NBTI/src/main/java/com/dao/nbti/objection/exception/ObjectionException.java
- NBTI/src/main/java/com/dao/nbti/study/domain/repository/StudyResultRepository.java
closes #19
closes #20
closes #17
---
📌 개요
🔨 주요 변경 사항
TestResultSummaryResponse.java 수정
- ObjectionController.java
- ObjectionDetailResponse.java
- ObjectionCreateRequest.java
- ObjectionCreateResponse.java
- ObjectionService.java
- ObjectionServiceImpl.java
- ObjectionRepository.java
- ObjectionException.java
- ErrorCode.java
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
> [refactor] 중복되는 점수 속성 개선 & 이의 제기 목록 조회 기능 구현

- NBTI/src/main/java/com/dao/nbti/study/domain/repository/StudyResultRepository.java
closes #12
closes #16
---
📌 개요
🔨 주요 변경 사항
- StudyResultRepository.java
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
> refactor : 풀이 문제 확인 로직 수정

- NBTI/src/main/java/com/dao/nbti/objection/application/controller/ObjectionController.java
- NBTI/src/main/java/com/dao/nbti/objection/application/service/ObjectionService.java
- NBTI/src/main/java/com/dao/nbti/objection/application/service/ObjectionServiceImpl.java
- NBTI/src/main/java/com/dao/nbti/objection/domain/repository/ObjectionRepository.java
closes #18
---
📌 개요
🔨 주요 변경 사항
- ObjectionController,java
- ObjectionService.java
- ObjectionServiceImpl.java
- ObjectionServiceImpl.java
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
> refactor : 이의제기 목록 조회 페이지 네이션 추가

- NBTI/src/main/java/com/dao/nbti/test/domain/aggregate/IsSaved.java
- NBTI/src/main/java/com/dao/nbti/test/domain/aggregate/TestResult.java
closes
---
📌 개요
TestResult 엔티티 수정
🔨 주요 변경 사항
- `IsSaved` enum 값으로 추가
- `TestResult`에 isSaved 컬럼 추가
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
> fix : testResult 엔티티 수정

- NBTI/src/main/java/com/dao/nbti/test/domain/repository/TestResultRepository.java
---
📌 개요
🔨 주요 변경 사항
- TestResultRepository
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
> refactor : 검사 결과 목록 조회에 새로이 추가된 isSaved 조건 검색 추가

- NBTI/src/main/java/com/dao/nbti/test/domain/repository/TestResultRepository.java
---
📌 개요
🔨 주요 변경 사항
- TestResultRepository.java
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
> refactor: isSaved 타입 오류 수정

- NBTI/src/main/java/com/dao/nbti/user/application/controller/UserController.java
- NBTI/src/main/java/com/dao/nbti/user/application/dto/UserInfoResponse.java
- NBTI/src/main/java/com/dao/nbti/user/application/service/UserService.java
closes #43 
---
📌 개요
회원은 자신의 아이디, 이름, 생년월일, 성별, 포인트 등의 정보를 조회 및 필터링할 수 있다.
🔨 주요 변경 사항
UserController.getUserInfo 메소드 구현
UserService.getUserInfo 메소드 구현
UserInfoResponse 클래스 추가
✅ 리뷰 요청 사항
회원 정보 조회 로직 확인
⭐ 관련 이슈
#43
> feat: 회원 정보 조회 기능 구현

- NBTI/src/main/java/com/dao/nbti/test/domain/repository/TestResultRepository.java
closes 
---
📌 개요
검사에서 누락된 메소드 복구
🔨 주요 변경 사항
- 누락된 `findLatestByUserId` 생성
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
> fix : 누락된 메소드 복구

- NBTI/src/main/java/com/dao/nbti/common/exception/ErrorCode.java
- NBTI/src/main/java/com/dao/nbti/problem/domain/repository/ProblemTestRepository.java
- NBTI/src/main/java/com/dao/nbti/test/application/controller/TestController.java
- NBTI/src/main/java/com/dao/nbti/test/application/service/TestService.java
- NBTI/src/main/java/com/dao/nbti/test/application/service/TestServiceImpl.java
- NBTI/src/test/java/com/dao/nbti/test/application/service/TestServiceImplTest.java
closes #42
---
📌 개요
문제 제공 기능 구현 완료
🔨 주요 변경 사항
- `ErrorCode` 추가
- `TestController`검사 문제 제공 controller 완성
- `TestService, TestServiceImpl` 검사 문제 제공 메서드 구현 완료
- 회원, 비회원 여부에 따라 맛보기 검사 & 일반 검사 진행
- `ProblemTestRespository` 생성해 문제 제공하는 메서드 및 쿼리 작성
✅ 리뷰 요청 사항
코드 로직 점검
⭐ 관련 이슈
#42
> feat : 검사 문제 제공 기능 구현 완료

- NBTI/src/main/java/com/dao/nbti/problem/domain/repository/AnswerTypeRepository.java
- NBTI/src/main/java/com/dao/nbti/problem/domain/repository/CategoryRepository.java
- NBTI/src/main/java/com/dao/nbti/problem/domain/repository/ProblemRepository.java
- NBTI/src/main/java/com/dao/nbti/study/application/controller/AdminStudyController.java
- NBTI/src/main/java/com/dao/nbti/study/application/dto/request/StudySearchRequestDto.java
- NBTI/src/main/java/com/dao/nbti/study/application/dto/response/StudySummaryDto.java
- NBTI/src/main/java/com/dao/nbti/study/application/dto/response/StudySummaryListResponseDto.java
- NBTI/src/main/java/com/dao/nbti/study/application/service/StudyService.java
- NBTI/src/main/java/com/dao/nbti/study/domain/repository/StudyRepository.java
- NBTI/src/main/java/com/dao/nbti/study/domain/repository/StudyRepositoryCustom.java
- NBTI/src/main/java/com/dao/nbti/study/domain/repository/StudyRepositoryImpl.java
- NBTI/src/main/java/com/dao/nbti/study/domain/repository/StudyResultRepository.java
closes #47 
---
📌 개요
학습 내역 조회 api 구현
🔨 주요 변경 사항
- CustomRepository 인터페이스와 이를 상속받는 StudyRepsitoryImpl 클래스에서 동적쿼리 로직 구현
- userId, categoryId(상위 분야), startDate, endDate를 기준으로 동적 쿼리 작성
✅ 리뷰 요청 사항
⭐ 관련 이슈
#47
> feat: 학습 내역 조회 api 구현

- NBTI/src/main/java/com/dao/nbti/common/auth/application/controller/AuthController.java
closes #92
---
📌 개요
로그인 HTTP 메소드 수정
🔨 주요 변경 사항
로그인 메소드 POST로 변경
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
> fix: 로그인 HTTP 메소드 수정

- NBTI/src/main/java/com/dao/nbti/problem/application/dto/response/ProblemSummaryDTO.java
- NBTI/src/main/java/com/dao/nbti/problem/domain/repository/ProblemRepositoryImpl.java
closes null
---
📌 개요
- 문제 목록 조회 수정
🔨 주요 변경 사항
- 문제 목록 조회 시 프론트에 답안 유형이 표시되지 않아 해당 부분 수정
✅ 리뷰 요청 사항
⭐ 관련 이슈
#27
> refactor: 문제 목록 조회 수정

- NBTI/build.gradle
- NBTI/src/main/java/com/dao/nbti/common/config/S3Config.java
- NBTI/src/main/java/com/dao/nbti/problem/application/controller/AdminProblemController.java
- NBTI/src/main/java/com/dao/nbti/problem/application/dto/request/ProblemCommandRequest.java
- NBTI/src/main/java/com/dao/nbti/problem/application/dto/request/ProblemCreateRequest.java
- NBTI/src/main/java/com/dao/nbti/problem/application/dto/request/ProblemUpdateRequest.java
- NBTI/src/main/java/com/dao/nbti/problem/application/service/AdminProblemService.java
- NBTI/src/main/java/com/dao/nbti/problem/application/service/S3Service.java
- NBTI/src/main/java/com/dao/nbti/problem/domain/aggregate/Problem.java
- NBTI/src/main/java/com/dao/nbti/study/application/dto/request/StudySearchRequestDto.java
- NBTI/src/main/resources/application.yml
closes #95 
---
📌 개요
S3 업로드 기반 문제 등록 수정 구현
🔨 주요 변경 사항
- 기존 ProblemCommandRequest에서 contentImageUrl 필드 제거 및 관련된 코드 리팩터링
- S3Config, S3Service 및 관련 의존성 추가
⭐ 관련 이슈
#95
> refactor: 관리자 문제 등록, 문제 수정시 S3 업로드 구현

- NBTI/src/main/java/com/dao/nbti/user/application/controller/UserController.java
closes #100
---
📌 개요
회원가입 HTTP 메소드 수정
🔨 주요 변경 사항
회원가입 HTTP 메소드 수정
✅ 리뷰 요청 사항
⭐ 관련 이슈
#100
> [fix #100] 회원가입 HTTP 메소드 수정

- NBTI/src/main/java/com/dao/nbti/objection/application/controller/ObjectionController.java
- NBTI/src/main/java/com/dao/nbti/objection/application/dto/response/ObjectionSummaryResponse.java
- NBTI/src/main/java/com/dao/nbti/objection/application/service/ObjectionService.java
- NBTI/src/main/java/com/dao/nbti/objection/application/service/ObjectionServiceImpl.java
- NBTI/src/main/java/com/dao/nbti/study/application/controller/StudyResultController.java
- NBTI/src/main/java/com/dao/nbti/study/application/dto/response/StudyProblemDetail.java
- NBTI/src/main/java/com/dao/nbti/study/application/dto/response/StudySummaryListResponseDto.java
- NBTI/src/main/java/com/dao/nbti/study/application/service/StudyResultServiceImpl.java
- NBTI/src/main/java/com/dao/nbti/study/domain/repository/StudyRepository.java
- NBTI/src/main/java/com/dao/nbti/test/application/controller/TestResultController.java
- NBTI/src/main/java/com/dao/nbti/test/application/service/TestResultServiceImpl.java
closes 
---
📌 개요
🔨 주요 변경 사항
- TestResultServiceImpl.java
- TestResultController.java
- StudyResultController.java
- ObjectionController.java
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
> refactor : 사용자 인증 관련 로직 수정

- NBTI/src/main/java/com/dao/nbti/problem/domain/repository/ProblemRepositoryImpl.java
closes #000
---
📌 개요
- 문제 목록 조회 시 정렬 로직 추가
🔨 주요 변경 사항
- 문제 ID 기준 오름차순으로 정렬
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
> refactor: 문제 목록 조회 시 정렬 로직 추가

- NBTI/src/main/java/com/dao/nbti/common/auth/application/controller/AuthController.java
- NBTI/src/main/java/com/dao/nbti/study/application/dto/request/StudySearchRequestDto.java
- NBTI/src/main/java/com/dao/nbti/test/domain/repository/TestRepositoryCustomImpl.java
- NBTI/src/main/java/com/dao/nbti/user/application/controller/UserController.java
- NBTI/src/main/java/com/dao/nbti/user/domain/aggregate/User.java
closes #103 
---
📌 개요
학습 목록 조회 로직 수정
User API 메소드 변경
사용자 초기 데이터 5포인트로 변경
🔨 주요 변경 사항
✅ 리뷰 요청 사항
코드 올바른지 확인
⭐ 관련 이슈
#103
> fix: 백엔드 로직 수정

- NBTI/src/main/java/com/dao/nbti/study/application/dto/response/StudyResultDetailResponseDto.java
- NBTI/src/main/java/com/dao/nbti/study/application/service/StudyService.java
> [refactor] 학습 결과 조회 시 정답 컬럼 추가

- NBTI/src/main/java/com/dao/nbti/study/application/dto/response/ProblemResponseDto.java
- NBTI/src/main/java/com/dao/nbti/study/application/service/StudyService.java
> refactor: 학습 문제 조회 시 정답 컬럼 추가

- NBTI/src/main/java/com/dao/nbti/study/domain/repository/StudyRepository.java
- NBTI/src/main/java/com/dao/nbti/test/domain/repository/TestResultRepository.java
closes #000
---
📌 개요
🔨 주요 변경 사항
- 이의제기 목록조회 최신 정렬 적용
- 학습 내역 조호 ㅣ최신 정렬 적용
- 검사 결과 내역 조회 최신 정렬 적용
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
> feat : 최신 정렬 적용

- NBTI/src/main/java/com/dao/nbti/study/application/dto/response/StudySummaryDto.java
- NBTI/src/main/java/com/dao/nbti/study/application/service/StudyService.java
- NBTI/src/main/java/com/dao/nbti/study/domain/repository/StudyRepositoryImpl.java
📌 개요
학습 문제 조회 시 isCorrect 검사 로직 제거
> fix: 학습 문제 조회 시 isCorrect 검사 로직 제거

- NBTI/src/main/java/com/dao/nbti/objection/application/controller/AdminObjectionController.java
- NBTI/src/main/java/com/dao/nbti/objection/application/dto/request/AdminObjectionSearchRequest.java
- NBTI/src/main/java/com/dao/nbti/objection/application/dto/request/ObjectionUpdateRequest.java
- NBTI/src/main/java/com/dao/nbti/problem/application/controller/AdminProblemController.java
- NBTI/src/main/java/com/dao/nbti/problem/application/dto/request/ProblemCreateRequest.java
- NBTI/src/main/java/com/dao/nbti/problem/application/dto/request/ProblemSearchRequest.java
- NBTI/src/main/java/com/dao/nbti/problem/application/dto/request/ProblemUpdateRequest.java
📌 개요
- swagger 문서화 주석 추가
🔨 주요 변경 사항
- `@Parameter`, `@Schema` 추가
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
> docs: swagger 주석 추가

- NBTI/src/main/java/com/dao/nbti/test/application/controller/TestResultController.java
- NBTI/src/main/java/com/dao/nbti/test/application/dto/response/TestResultResponse.java
- NBTI/src/main/java/com/dao/nbti/test/application/service/TestService.java
- NBTI/src/main/java/com/dao/nbti/test/application/service/TestServiceImpl.java
closes #112 
---
📌 개요
프론트에서 검사 결과 조회 시 발생하는 버그 해결을 위한 백엔드 코드 수정
🔨 주요 변경 사항
- 비회원의 최고 점수는 2점인것을 반영하기 위해 테스트 결과 조회 시 userId도 받아올 수 있게 수정
- `TestResultController`, `TestService` , `TestServiceImpl` 에서 반환 값을 TestResultResponse로 수정
- TestResultResponse`에 scores(점수 정보), userId, aiText를 받는 응답 추가
✅ 리뷰 요청 사항
로직 점검
⭐ 관련 이슈
#112
> fix : 검사 결과 조회 수정

- NBTI/src/main/java/com/dao/nbti/common/auth/application/controller/AuthController.java
- NBTI/src/main/java/com/dao/nbti/user/application/controller/UserController.java
- NBTI/src/main/java/com/dao/nbti/user/application/dto/UserDeleteRequest.java
- NBTI/src/main/java/com/dao/nbti/user/application/service/UserService.java
- NBTI/src/test/java/com/dao/nbti/user/application/service/UserServiceTest.java
closes #114 
---
📌 개요
🔨 주요 변경 사항
회원 탈퇴시 비밀번호 request 추가
✅ 리뷰 요청 사항
회원 비밀번호 요청 로직 검사
테스트코드 정상 동작 확인
⭐ 관련 이슈
#114
> fix: 회원 탈퇴 request 추가

- NBTI/src/main/java/com/dao/nbti/common/config/SecurityConfig.java
closes #000
---
📌 개요
- admin 문제 관리 및 이의 제기 관리 엔드포인트에 대한 security 설정
🔨 주요 변경 사항
- permitAll에서 관리자 엔드포인트 설정
✅ 리뷰 요청 사항
- security 설정이 적절한지
⭐ 관련 이슈
#
> feat: spring security 설정

- NBTI/Dockerfile
- docker-compose.yml
closes #000
---
📌 개요
Dockerfile, docker-compose 추가
🔨 주요 변경 사항
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
> [docs] Dockerfile, docker-compose 추가

- docker/logstash/logstash.conf
> docs: logstash.conf 파일 추가

- NBTI/src/main/java/com/dao/nbti/common/config/SecurityConfig.java
📌 개요
- 새로고침 시 다시 로그인을 요청하는 문제 수정
🔨 주요 변경 사항
- permitAll 엔드포인트에 `/auth/refresh` 추가
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
> [fix] security config 수정

- NBTI/src/test/java/com/dao/nbti/NbtiApplicationTests.java
- docker-compose.yml
backend container 제거, 불필요한 test contextLoad문 제거
> chore: backend container 제거, 불필요한 test contextLoad문 제거

- NBTI/build.gradle
- NBTI/src/main/resources/application.yml
- NBTI/src/main/resources/logback-spring.xml
> feat: logstash, spring actuator 의존성

- NBTI/src/main/java/com/dao/nbti/common/config/SecurityConfig.java
closes #000
---
📌 개요
🔨 주요 변경 사항
✅ 리뷰 요청 사항
⭐ 관련 이슈
#
> [init] swagger api 인증 허가

- NBTI/src/main/java/com/dao/nbti/common/auth/application/service/AuthService.java
> chore: 로그인 시, slf4j log 출력문 추가

- NBTI/src/main/java/com/dao/nbti/common/auth/application/service/AuthService.java
> chore: 로그아웃 시, slf4j log 출력문 수정
